config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, :controllers => { :registrations => :registrations }
  root "directors#index"
  resources :users, only: [:index, :show]
  resources :movies do 
    resources :reviews, except: [:show, :index]
  end
  resources :directors
  resources :results, only: [:index]

end

app/models/director.rb
class Director < ActiveRecord::Base
  validates_uniqueness_of :name
  validates :name, :country, :picture, :description, presence: true
  has_many :movies

  mount_uploader :picture, PicUploader
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  before_action :set_director, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @directors = Director.all
  end

  def show
  end

  def new
    @director = Director.new
  end

  def edit
  end

  def create
    @director = Director.new(director_params)

    respond_to do |format|
      if @director.save
        flash[:success] = "Director was successfully created."
        format.html { redirect_to @director}
        format.json { render :show, status: :created, location: @director }
      else
        flash[:alert] = 'There was a problem creating the Director.'
        format.html { render :new }
        format.json { render json: @director.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @director.update(director_params)
        flash[:success] = "Director was successfully updated."
        format.html { redirect_to @director }
        format.json { render :show, status: :ok, location: @director }
      else
        flash[:alert] = 'There was a problem updating the Director.'
        format.html { render :edit }
        format.json { render json: @director.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if current_user.try(:admin?)
      @director.destroy
      respond_to do |format|
        flash[:success] = "Director was successfully destroyed."
        format.html { redirect_to directors_url }
        format.json { head :no_content }
      end
    end
  end

  private
    def set_director
      @director = Director.find(params[:id])
    end

    def director_params
      params.require(:director).permit(:name, :description, :country, :picture)
    end
end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/views/directors/_form.html.erb
<%= form_for(@director) do |f| %>

  <div class="row">
    <div class="small-8 columns">
      <div class="large-2 columns">
        <%= f.label :name, class: "left inline" %><br>
      </div>
      <div class="large-10 columns">
        <%= f.text_field :name %>
        <% if @director.errors[:name][0] %>
          <small class="error"><%= @director.errors[:name][0] %></small>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="small-8 columns">
      <div class="large-2 columns">
        <%= f.label :country, class: "left inline" %><br>
      </div>
      <div class="large-10 columns">
        <%= f.text_field :country %>
        <% if @director.errors[:country][0] %>
          <small class="error"><%= @director.errors[:country][0] %></small>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="small-8 columns">
      <div class="large-2 columns">
        <%= f.label :picture, class: "left inline" %><br>
      </div>
      <div class="large-10 columns">
        <%= f.file_field :picture %>
        <% if @director.errors[:picture][0] %>
          <small class="error"><%= @director.errors[:picture][0] %></small>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="small-8 columns">
      <div class="large-2 columns">
        <%= f.label :description, class: "left inline" %><br>
      </div>
      <div class="large-10 columns">
        <%= f.text_area :description %>
        <% if @director.errors[:description][0] %>
          <small class="error"><%= @director.errors[:description][0] %></small>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="small-8 columns">
      <%= f.submit class: "button small"%>
    </div>
  </div>

<% end %>

app/views/directors/edit.html.erb
<header class="row"> 
  <h1>Editing Director</h1>
</header>
<section class="row">
  <%= render 'form' %>
</section>

app/views/directors/index.html.erb
<div class="directors-index">
  <header class="row index">
    <h1 class="animated fadeInLeft">Directors</h1>
  </header>
  <div class="row index">
    <div class="medium-8 medium-offset-2 columns">
      <ul class="medium-block-grid-2">
        <% @directors.each do |director| %>
          <li>
            <header class="director-title">
              <div>
                <%= director.name %>
              </div>
              <div>
                <em><%= director.country %></em>
              </div>
            </header>
            <section>
              <%= link_to image_tag(director.picture), director %>
            </section>
            <footer>
              <div class="row">
                <div class="medium-8 medium-centered columns">
                  <%= link_to 'Edit', edit_director_path(director), class: "button round radius info expand" %>
                </div>
              </div>
              <div class="row">
                <div class="medium-8 medium-centered columns">
                  <% if current_user.try(:admin?) %>
                    <%= link_to 'Destroy', director, method: :delete, data: { confirm: 'Are you sure?' } %>
                  <% end %>
                </div>
              </div>
            </footer>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/directors/new.html.erb
<header class="row"> 
  <h1>New Director</h1>
</header>
<section class="row">
  <%= render 'form' %>
</section>

app/views/directors/show.html.erb
<div class="row director-show">
  <header class="director-title small-3 small-centered columns">
    <%= @director.name %>
    <%= @director.country %>
  </header>
</div>
<div class="row director-show">
  <section class="medium-offset-2 medium-3 columns">
    <%= image_tag @director.picture %>
  </section>
  <aside class="medium-4 columns end">
    <p><%= @director.description %></p>
  </aside>
</div>
<div class="row director-show">
  <footer>
    <div class="medium-offset-2 medium-6 columns">
      <select name="movies" onchange="location = this.value">
        <option>Movies</option>
        <% @director.movies.each do |movie| %>
          <option value="<%= movie_path(movie) %>">
            <%= movie.name %>
          </option>
        <% end %>
      </select>
    </div>
    <div class="medium-2 columns end">
      <%= link_to 'Edit', edit_director_path(@director), class: "button tiny" %>
    </div>
  </footer>
</div>