config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, :controllers => { :registrations => :registrations }
  root "directors#index"
  resources :users, only: [:index, :show]
  resources :movies do 
    resources :reviews, except: [:show, :index]
  end
  resources :directors
  resources :results, only: [:index]

end

app/views/layouts/_top_bar.html.erb
<div class="contain-to-grid">
  <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
      <li class="name">
        <h1><%= link_to 'Pmdb', root_path %></h1>
      </li>
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>

    <section class="top-bar-section">
      <ul class="left">
        <% if user_signed_in? %>
          <li class="has-dropdown">
          <%= link_to current_user.username, '#' %>
          <ul class="dropdown">
            <li><%= link_to 'My Page', current_user %></li>
            <li><%= link_to 'Account', edit_user_registration_path %></li>
            <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          </ul>
        <% else %>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <% end %>
      </ul>

      <ul>
        <li class="has-form">
          <%= form_tag( results_path, method: "get") do %>
            <div class="row collapse">
              <div class="large-8 small-9 columns">
                <%= text_field_tag :q, nil, placeholder: "Movie Title" %>
              </div>
              <div class="large-4 small-3 columns">
                <button class="alert button expand">Search</button>
              </div>
            </div>
          <% end %>
        </li>
      </ul>

      <ul class="right">
        <li class="has-dropdown">
          <a href="#">Directors</a>
          <ul class="dropdown">
            <li><%= link_to 'All', directors_path %></li>
            <li><%= link_to 'New Director', new_director_path %></li>
          </ul>
        </li>
        <li class="has-dropdown">
          <a href="#">Movies</a>
          <ul class="dropdown">
            <li><%= link_to 'All', movies_path %></li>
            <li><%= link_to 'New Movie', new_movie_path %></li>
          </ul>
        </li>

        <li><%= link_to 'Users', users_path %></li>

      </ul>
    </section>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Pmdb</title>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Josefin+Sans:400,300,100,700,600" %>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/top_bar' %>

    <div class="row flash">
      <% flash.each do |name, msg| %>
        <% if msg.is_a?(String) %>
          <%= content_tag :div, msg, class: "alert-box #{name} radius" %>
        <% end %>
      <% end %>
    </div>

    
    <%= yield %>

  </body>
</html>